import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppProvider } from "@/context/AppContext";
import Bprogress from "@/components/Bprogrss";
import { Toaster } from "sonner";
import PaymentModalWrapper from "@/components/modals/PaymentModal/PaymentModalWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppProvider>
      <html lang='en'>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <Bprogress>
            <div className='route-wrapper'>
              <Toaster richColors position='top-center' />
              {children}
            </div>
            <PaymentModalWrapper />
          </Bprogress>
        </body>
      </html>
    </AppProvider>
  );
}
